AWSTemplateFormatVersion: '2010-09-09'
Description: 'API CRUD Flask + SQLite en ECS Fargate con ALB'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC (usa la default)

  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subredes publicas (2+)

  ImageUri:
    Type: String
    Description: URI de imagen ECR

  ContainerPort:
    Type: Number
    Default: 8000  

  DesiredCount:
    Type: Number
    Default: 1

  LabRoleArn:
    Type: String
    Default: arn:aws:iam::478701513931:role/LabRole
    Description: Rol IAM provisto por el laboratorio (TaskRole/ExecutionRole)

Resources:
  AlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG ALB publico
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  TasksSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG tareas solo desde ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref AlbSG

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: fargate-crud-alb
      Scheme: internet-facing
      Subnets: !Ref PublicSubnets
      SecurityGroups: [!Ref AlbSG]
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: fargate-crud-tg
      VpcId: !Ref VpcId
      TargetType: ip
      Protocol: HTTP
      Port: !Ref ContainerPort
      HealthCheckPath: /students
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      Matcher:
        HttpCode: '200'

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/fargate-crud
      RetentionInDays: 7

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: fargate-crud-cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-crud-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref LabRoleArn
      TaskRoleArn: !Ref LabRoleArn
      ContainerDefinitions:
        - Name: api
          Image: !Ref ImageUri
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: api

  Service:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      ServiceName: fargate-crud-svc
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      PlatformVersion: LATEST
      DesiredCount: !Ref DesiredCount
      HealthCheckGracePeriodSeconds: 60
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: [!Ref TasksSG]
          Subnets: !Ref PublicSubnets
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerName: api
          ContainerPort: !Ref ContainerPort
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      SchedulingStrategy: REPLICA

Outputs:
  AlbDNS:
    Description: URL del ALB
    Value: !GetAtt ALB.DNSName
  ServiceName:
    Description: Nombre del servicio ECS
    Value: !Ref Service

